# These are supported funding model platforms

github: [sanskaarz]
patreon: sanskaarz
open_collective: # Replace with a single Open Collective username
ko_fi: sanskaarz
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: 
liberapay: sanskaarz
issuehunt: sanskaarz
lfx_crowdfunding: 
polar: sanskaarz
buy_me_a_coffee: sanskaarz
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
